#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

OPENAI_BASE_URL=https://api.deepseek.com/v1
OPENAI_API_KEY=$DEEPSEEK_API_KEY
JUDGE_MODEL=deepseek-v4-flash
POLICY_MODEL=Qwen/Qwen3-4B-Instruct-2507
OUTPUT_DIR=runs/trl-grpo
TRAIN_GPUS=2,3,4,5      # comma-separated GPU indices
NUM_GPUS=4               # must match the number of indices above
BATCH_SIZE=2
GRAD_ACCUM=2
NUM_GENERATIONS=4
MAX_PROMPT_LEN=1024
MAX_COMPLETION_LEN=1600
LR=1e-5
KL_BETA=0.04
TEMPERATURE=1.0
MAX_STEPS=200
LORA_R=16
LORA_ALPHA=32
N_EXAMPLES=3000
USE_WANDB=0
COLLECT_ONLY=0

mkdir -p "$OUTPUT_DIR"

CUDA_VISIBLE_DEVICES="$TRAIN_GPUS" \
OPENAI_BASE_URL="$OPENAI_BASE_URL" \
OPENAI_API_KEY="$OPENAI_API_KEY" \
JUDGE_MODEL="$JUDGE_MODEL" \
POLICY_MODEL="$POLICY_MODEL" \
OUTPUT_DIR="$OUTPUT_DIR" \
ROLLOUT_LOG="$OUTPUT_DIR/rollouts.jsonl" \
TRACE_LOG="$OUTPUT_DIR/traces.jsonl" \
BATCH_SIZE="$BATCH_SIZE" \
GRAD_ACCUM="$GRAD_ACCUM" \
NUM_GENERATIONS="$NUM_GENERATIONS" \
MAX_PROMPT_LEN="$MAX_PROMPT_LEN" \
MAX_COMPLETION_LEN="$MAX_COMPLETION_LEN" \
LR="$LR" \
KL_BETA="$KL_BETA" \
TEMPERATURE="$TEMPERATURE" \
MAX_STEPS="$MAX_STEPS" \
LORA_R="$LORA_R" \
LORA_ALPHA="$LORA_ALPHA" \
N_EXAMPLES="$N_EXAMPLES" \
USE_WANDB="$USE_WANDB" \
COLLECT_ONLY="$COLLECT_ONLY" \
uv run accelerate launch \
  --num_processes "$NUM_GPUS" \
  --mixed_precision bf16 \
  -m gavel.trl_grpo.train
